# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Geodedb < Formula
  desc "ISO/IEC 39075:2024 GQL-compliant property-graph database"
  homepage "https://gitlab.com/devnw/codepros/geode/geode"
  version "0.1.4"
  license "Apache-2.0"
  depends_on :macos

  url "https://gitlab.com/devnw/codepros/geode/geode/-/jobs/artifacts/v0.1.4/raw/dist/geode_0.1.4_darwin_universal.tar.gz?job=build-release", using: CurlDownloadStrategy
  sha256 "4dbfde0ba11e60425ad0ae81bf9d1507641d95a3bc7e9a1097eff2def8ee3009"

  def install
    bin.install "geode"
  end

  def caveats
    <<~EOS
      Geode has been installed!

      Note: This is 'geodedb' (GQL graph database), not Apache Geode.

      To start the server:
        geode serve --listen 0.0.0.0:3141

      To use the interactive shell:
        geode shell

      Documentation: https://gitlab.com/devnw/codepros/geode/geode/-/tree/main/docs
    EOS
  end

  test do
    system "#{bin}/geode", "--version"
  end
end
