# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Geode < Formula
  desc "ISO/IEC 39075:2024 GQL-compliant property-graph database"
  homepage "https://geodedb.com"
  version "0.1.10"
  license "Apache-2.0"

  depends_on "openssl@3"
  depends_on :macos

  url "https://gitlab.com/api/v4/projects/devnw%2Fcodepros%2Fgeode%2Fgeode/packages/generic/geode/0.1.10/geode_0.1.10_darwin_universal.tar.gz"
  sha256 "4190fc4877c4c6f6d683cf22bd3fd9a73a205a23a841806beeb2dc0e8189ecaf"

  def install
    bin.install "geode"
    (var/"lib/geode").mkpath
    (var/"log/geode").mkpath
    (etc/"geode").mkpath
    (etc/"geode/certs").mkpath
  end

  def caveats
    <<~EOS
      Geode Graph Database has been installed!

      Note: This is Geode Graph Database (geodedb.com), not Apache Geode.

      To start the server:
        geode serve --listen 0.0.0.0:3141

      To use the interactive shell:
        geode shell

      To run as a service:
        brew services start geode

      Data: #{var}/lib/geode
      Logs: #{var}/log/geode

      Documentation: https://geodedb.com/docs
    EOS
  end

  service do
    run [opt_bin/"geode", "serve", "--listen", "0.0.0.0:3141", "--data-dir", var/"lib/geode"]
    keep_alive true
    working_dir var/"lib/geode"
    log_path var/"log/geode/geode.log"
    error_log_path var/"log/geode/geode.error.log"
  end

  test do
    system "#{bin}/geode", "--version"
  end
end
