# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Geode < Formula
  desc "ISO/IEC 39075:2024 GQL-compliant property-graph database"
  homepage "https://gitlab.com/devnw/codepros/geode/geode"
  version "0.1.4-alpha.3"
  license "Apache-2.0"
  depends_on :macos

  url "https://gitlab.com/devnw/codepros/geode/geode/-/releases/v0.1.4-alpha.3/downloads/geode_0.1.4-alpha.3_darwin_universal.tar.gz", using: CurlDownloadStrategy
  sha256 "f1f692cc7a99eb49da5d9c7c3950e338bf0d1ce358bc1e39ae00287550eafda7"

  def install
    bin.install "geode"
  end

  test do
    system "#{bin}/geode", "--version"
  end
end
